/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proveedor;

import Cuentas.buscaCuentas;
import Hibernate.Util.HibernateUtil;
import Hibernate.entidades.Cuentas;
import Hibernate.entidades.Proveedor;
import Hibernate.entidades.UsoCfdi;
import Hibernate.entidades.Usuario;
import static datechooser.beans.PermanentBean.dispose;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.InputMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.HibernateException;
import org.hibernate.Query;
import org.hibernate.Session;
import Integral.Herramientas;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import org.hibernate.criterion.Restrictions;
import sat.buscaUsoCfdi;
/**
 *
 * @author ESPECIALIZADO TOLUCA
 */
public class nuevoProveedor extends javax.swing.JPanel {

    /**
     * Creates new form nuevoProveedor
     */
    
    public static final Proveedor RET_CANCEL =null;
    InputMap map = new InputMap();
    DefaultTableModel model;
    Usuario user;
    String sessionPrograma="";
    Herramientas h;
    private Proveedor returnStatus;
    //Proveedor registro = null;
    
    public nuevoProveedor(Usuario usuario, String envio_periodo, String ses) {
        sessionPrograma=ses;
        user=usuario;
        initComponents();
        coi.setIcon(new ImageIcon("imagenes/cuenta.png"));
        cp.setIcon(new ImageIcon("imagenes/cuenta.png"));
    }
    
    private void doClose(Proveedor o) {
        returnStatus = o;
        setVisible(false);
        dispose();
    }
    
    public Proveedor getReturnStatus() {
        return returnStatus;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b_guardar = new javax.swing.JButton();
        b_cancelar = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        l_importe_compras2 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        l_importe_compras3 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        l_nombre = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        t_notas = new javax.swing.JTextArea();
        t_nombre = new javax.swing.JTextField();
        l_estado = new javax.swing.JLabel();
        t_estado = new javax.swing.JComboBox();
        l_direccion = new javax.swing.JLabel();
        t_direccion = new javax.swing.JTextField();
        l_rfc = new javax.swing.JLabel();
        t_rfc = new javax.swing.JTextField();
        l_telefono1 = new javax.swing.JLabel();
        t_telefono1 = new javax.swing.JTextField();
        l_colonia = new javax.swing.JLabel();
        t_colonia = new javax.swing.JTextField();
        l_telefono2 = new javax.swing.JLabel();
        t_telefono2 = new javax.swing.JTextField();
        l_fax = new javax.swing.JLabel();
        t_fax = new javax.swing.JTextField();
        l_poblacion = new javax.swing.JLabel();
        t_poblacion = new javax.swing.JTextField();
        l_cp = new javax.swing.JLabel();
        t_cp = new javax.swing.JTextField();
        l_email = new javax.swing.JLabel();
        t_email = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        l_representante1 = new javax.swing.JLabel();
        t_representante = new javax.swing.JTextField();
        l_puesto1 = new javax.swing.JLabel();
        t_cuenta = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        l_credito_limite = new javax.swing.JLabel();
        l_credito_plazo = new javax.swing.JLabel();
        l_credito_descuento = new javax.swing.JLabel();
        t_credito_descuento = new javax.swing.JTextField();
        t_credito_plazo = new javax.swing.JTextField();
        t_credito_limite = new javax.swing.JTextField();
        l_tiempo_entrega = new javax.swing.JLabel();
        t_tiempo_entrega = new javax.swing.JTextField();
        l_importe_compras = new javax.swing.JLabel();
        t_importe_compras = new javax.swing.JTextField();
        l_tipo = new javax.swing.JLabel();
        t_tipo = new javax.swing.JComboBox();
        jPanel7 = new javax.swing.JPanel();
        checkhoja = new javax.swing.JCheckBox();
        espmeca = new javax.swing.JCheckBox();
        espelec = new javax.swing.JCheckBox();
        espsusp = new javax.swing.JCheckBox();
        t_giro = new javax.swing.JTextField();
        l_giro = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        l_importe_compras1 = new javax.swing.JLabel();
        l_tipo1 = new javax.swing.JLabel();
        cuenta_coi = new javax.swing.JTextField();
        cuenta_concepto = new javax.swing.JTextField();
        coi = new javax.swing.JButton();
        cp = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        t_id_cfdi = new javax.swing.JTextField();
        t_descripcion_cfdi = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        b_guardar.setBackground(new java.awt.Color(2, 135, 242));
        b_guardar.setForeground(new java.awt.Color(254, 254, 254));
        b_guardar.setIcon(new ImageIcon("imagenes/guardar.png"));
        b_guardar.setText("Guardar");
        b_guardar.setToolTipText("Guarda el registro actual");
        b_guardar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        b_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_guardarActionPerformed(evt);
            }
        });

        b_cancelar.setBackground(new java.awt.Color(2, 135, 242));
        b_cancelar.setForeground(new java.awt.Color(254, 254, 254));
        b_cancelar.setIcon(new ImageIcon("imagenes/cancelar.png"));
        b_cancelar.setText("Cancelar");
        b_cancelar.setToolTipText("Cancela el registro actual");
        b_cancelar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        b_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cancelarActionPerformed(evt);
            }
        });

        jLabel17.setText("Nota: Los campos en azul son obligatorios");

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Acceso Portal de Proveedores"));

        l_importe_compras2.setForeground(new java.awt.Color(51, 0, 255));
        l_importe_compras2.setText("Usuario:");

        usuario.setBackground(new java.awt.Color(204, 255, 255));
        usuario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                usuarioKeyTyped(evt);
            }
        });

        l_importe_compras3.setForeground(new java.awt.Color(51, 0, 255));
        l_importe_compras3.setText("Contraseña:");

        password.setBackground(new java.awt.Color(204, 255, 255));
        password.setMinimumSize(new java.awt.Dimension(6, 22));
        password.setPreferredSize(new java.awt.Dimension(6, 22));
        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passwordKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l_importe_compras2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_importe_compras3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(l_importe_compras3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(l_importe_compras2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        l_nombre.setForeground(new java.awt.Color(51, 0, 255));
        l_nombre.setText("Nombre:");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Notas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 11))); // NOI18N

        t_notas.setBackground(new java.awt.Color(204, 255, 255));
        t_notas.setColumns(20);
        t_notas.setRows(5);
        t_notas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_notasKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(t_notas);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                .addGap(8, 8, 8))
        );

        t_nombre.setBackground(new java.awt.Color(204, 255, 255));
        t_nombre.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        t_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_nombreKeyTyped(evt);
            }
        });

        l_estado.setText("Estado");

        t_estado.setBackground(new java.awt.Color(204, 255, 255));
        t_estado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-------", "Aguascalientes", "Baja California", "Baja California Sur", "Campeche", "Chiapas", "Chihuahua", "Coahuila", "Colima", "Ciudad de México", "Durango", "Estado de México", "Guanajuato", "Guerrero", "Hidalgo", "Jalisco", "Michoacán", "Morelos", "Nayarit", "Nuevo León", "Oaxaca", "Puebla", "Querétaro", "Quintana Roo", "San Luis Potosí", "Sinaloa", "Sonora", "Tabasco", "Tamaulipas", "Tlaxcala", "Veracruz", "Yucatán", "Zacatecas" }));

        l_direccion.setText("Dirección:");

        t_direccion.setBackground(new java.awt.Color(204, 255, 255));
        t_direccion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        t_direccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_direccionKeyTyped(evt);
            }
        });

        l_rfc.setForeground(new java.awt.Color(51, 0, 255));
        l_rfc.setText("R.F.C.:");

        t_rfc.setBackground(new java.awt.Color(204, 255, 255));
        t_rfc.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        t_rfc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_rfcKeyTyped(evt);
            }
        });

        l_telefono1.setText("Teléfono 1:");

        t_telefono1.setBackground(new java.awt.Color(204, 255, 255));
        t_telefono1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        t_telefono1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_telefono1KeyTyped(evt);
            }
        });

        l_colonia.setText("Colonia:");

        t_colonia.setBackground(new java.awt.Color(204, 255, 255));
        t_colonia.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        t_colonia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_coloniaKeyTyped(evt);
            }
        });

        l_telefono2.setText("Teléfono 2:");

        t_telefono2.setBackground(new java.awt.Color(204, 255, 255));
        t_telefono2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        t_telefono2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_telefono2KeyTyped(evt);
            }
        });

        l_fax.setText("Fax:");

        t_fax.setBackground(new java.awt.Color(204, 255, 255));
        t_fax.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        t_fax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_faxKeyTyped(evt);
            }
        });

        l_poblacion.setText("Población:");

        t_poblacion.setBackground(new java.awt.Color(204, 255, 255));
        t_poblacion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        t_poblacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_poblacionKeyTyped(evt);
            }
        });

        l_cp.setText("Cp:");

        t_cp.setBackground(new java.awt.Color(204, 255, 255));
        t_cp.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        t_cp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_cpKeyTyped(evt);
            }
        });

        l_email.setText("Email:");

        t_email.setBackground(new java.awt.Color(204, 255, 255));
        t_email.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        t_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_emailKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(l_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(l_estado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_estado, 0, 104, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(l_direccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(l_colonia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t_colonia, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                            .addComponent(t_direccion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(l_rfc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t_rfc)
                                .addGap(7, 7, 7)
                                .addComponent(l_telefono1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t_telefono1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(l_telefono2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t_telefono2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l_fax)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t_fax))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(l_poblacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_poblacion)
                        .addGap(84, 84, 84)
                        .addComponent(l_cp)
                        .addGap(18, 18, 18)
                        .addComponent(t_cp, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(141, 141, 141)
                        .addComponent(l_email)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_email))
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(l_estado)
                        .addComponent(t_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(l_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(t_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(l_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(t_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t_telefono1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l_telefono1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_rfc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l_rfc, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(t_colonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(l_colonia, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_telefono2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_telefono2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l_fax, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_fax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(l_email, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(t_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(l_poblacion, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(t_poblacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(l_cp, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(t_cp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Datos Generales", jPanel1);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Crédito", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 11))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Contacto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 11))); // NOI18N

        l_representante1.setText("Representante:");

        t_representante.setBackground(new java.awt.Color(204, 255, 255));
        t_representante.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        t_representante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_representanteKeyTyped(evt);
            }
        });

        l_puesto1.setText("Cuenta: ");

        t_cuenta.setBackground(new java.awt.Color(204, 255, 255));
        t_cuenta.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        t_cuenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_cuentaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(l_representante1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_representante))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(l_puesto1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_representante1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_representante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_puesto1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Credito"));

        l_credito_limite.setText("Crédito Límite: ");

        l_credito_plazo.setForeground(new java.awt.Color(51, 0, 255));
        l_credito_plazo.setText("Crédito Plazo:");

        l_credito_descuento.setForeground(new java.awt.Color(51, 0, 255));
        l_credito_descuento.setText("Crédito Descuento:");

        t_credito_descuento.setBackground(new java.awt.Color(204, 255, 255));
        t_credito_descuento.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        t_credito_descuento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_credito_descuentoFocusLost(evt);
            }
        });
        t_credito_descuento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_credito_descuentoKeyTyped(evt);
            }
        });

        t_credito_plazo.setBackground(new java.awt.Color(204, 255, 255));
        t_credito_plazo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        t_credito_plazo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_credito_plazoKeyTyped(evt);
            }
        });

        t_credito_limite.setBackground(new java.awt.Color(204, 255, 255));
        t_credito_limite.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        t_credito_limite.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_credito_limiteKeyTyped(evt);
            }
        });

        l_tiempo_entrega.setForeground(new java.awt.Color(51, 0, 255));
        l_tiempo_entrega.setText("Tiempo de entrega:");

        t_tiempo_entrega.setBackground(new java.awt.Color(204, 255, 255));
        t_tiempo_entrega.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        t_tiempo_entrega.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_tiempo_entregaKeyTyped(evt);
            }
        });

        l_importe_compras.setForeground(new java.awt.Color(51, 0, 255));
        l_importe_compras.setText("Imp/compras:");

        t_importe_compras.setBackground(new java.awt.Color(204, 255, 255));
        t_importe_compras.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        t_importe_compras.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_importe_comprasFocusLost(evt);
            }
        });
        t_importe_compras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_importe_comprasKeyTyped(evt);
            }
        });

        l_tipo.setForeground(new java.awt.Color(51, 0, 255));
        l_tipo.setText("Tipo:");

        t_tipo.setBackground(new java.awt.Color(204, 255, 255));
        t_tipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Servicios", "Materiales" }));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_credito_descuento)
                    .addComponent(l_credito_plazo)
                    .addComponent(l_credito_limite))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(t_credito_plazo)
                    .addComponent(t_credito_descuento)
                    .addComponent(t_credito_limite, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(l_tipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l_tiempo_entrega, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(l_importe_compras, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t_tiempo_entrega, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                            .addComponent(t_importe_compras))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_credito_limite, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_credito_limite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_tiempo_entrega, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_tiempo_entrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_credito_plazo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_credito_plazo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_importe_compras, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_importe_compras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_credito_descuento, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_credito_descuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 28, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Especialidad"));

        checkhoja.setText("Hojalatería");

        espmeca.setText("Mecánica");

        espelec.setText("Electricidad");

        espsusp.setText("Suspensión");

        t_giro.setBackground(new java.awt.Color(204, 255, 255));
        t_giro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        t_giro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_giroKeyTyped(evt);
            }
        });

        l_giro.setText("Giro:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkhoja)
                            .addComponent(espsusp))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(espmeca)
                            .addComponent(espelec))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(l_giro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_giro)))
                .addGap(10, 10, 10))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(espmeca)
                    .addComponent(checkhoja))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(espsusp)
                    .addComponent(espelec))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_giro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_giro, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Cuentas COI"));

        l_importe_compras1.setForeground(new java.awt.Color(51, 0, 255));
        l_importe_compras1.setText("Cuenta Concepto:");

        l_tipo1.setForeground(new java.awt.Color(51, 0, 255));
        l_tipo1.setText("Cuenta Proveedor COI:");

        cuenta_coi.setBackground(new java.awt.Color(204, 255, 255));
        cuenta_coi.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cuenta_coi.setEnabled(false);
        cuenta_coi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cuenta_coiKeyTyped(evt);
            }
        });

        cuenta_concepto.setBackground(new java.awt.Color(204, 255, 255));
        cuenta_concepto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cuenta_concepto.setEnabled(false);
        cuenta_concepto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cuenta_conceptoKeyTyped(evt);
            }
        });

        coi.setBackground(new java.awt.Color(2, 135, 242));
        coi.setForeground(new java.awt.Color(255, 255, 255));
        coi.setToolTipText("Agregar Cuenta COI");
        coi.setPreferredSize(new java.awt.Dimension(40, 25));
        coi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coiActionPerformed(evt);
            }
        });

        cp.setBackground(new java.awt.Color(2, 135, 242));
        cp.setForeground(new java.awt.Color(255, 255, 255));
        cp.setToolTipText("Agregar Cuenta Concepto");
        cp.setPreferredSize(new java.awt.Dimension(40, 25));
        cp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(l_tipo1)
                    .addComponent(l_importe_compras1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cuenta_coi, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                    .addComponent(cuenta_concepto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_tipo1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cuenta_coi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l_importe_compras1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(cuenta_concepto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(coi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(cp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Uso CFDI")));

        jButton1.setText("C");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        t_id_cfdi.setBackground(new java.awt.Color(204, 255, 255));
        t_id_cfdi.setEnabled(false);

        t_descripcion_cfdi.setBackground(new java.awt.Color(204, 255, 255));
        t_descripcion_cfdi.setEnabled(false);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_id_cfdi, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_descripcion_cfdi)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(t_id_cfdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(t_descripcion_cfdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Credito y contabilidad", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b_cancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_guardar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void b_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cancelarActionPerformed
        // TODO add your handling code here:
        h=new Herramientas(user, 0);
        h.session(sessionPrograma);
        t_nombre.requestFocus();    
        int opt=JOptionPane.showConfirmDialog(this, "¡Los datos capturados se eliminarán!");
        System.out.println(opt);
        if(opt==0)
            borra_cajas();
        t_nombre.requestFocus();
    }//GEN-LAST:event_b_cancelarActionPerformed

    private void b_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_guardarActionPerformed
        // TODO add your handling code here:
        h=new Herramientas(user, 0);
        h.session(sessionPrograma);
        b_cancelar.requestFocus();
        
        if(t_nombre.getText().compareTo("")!=0)
        {
            if(t_rfc.getText().compareTo("")!=0)
            {
                if(t_credito_plazo.getText().compareTo("")!=0)
                {
                    if(t_credito_descuento.getText().compareTo("")!=0)
                    {
                        if(t_tiempo_entrega.getText().compareTo("")!=0)
                        {
                            if(t_importe_compras.getText().compareTo("")!=0)
                            {                                
                                if(t_tipo.getItemCount()>0)
                                {
                                    if(consultaProveedor(t_rfc.getText())==false)
                                    {
                                        Proveedor registro = new Proveedor();

                                        if(t_nombre.getText().compareTo("")!=0)
                                            registro.setNombre(t_nombre.getText());
                                        if(t_direccion.getText().compareTo("")!=0)
                                            registro.setDireccion(t_direccion.getText());
                                        if(t_colonia.getText().compareTo("")!=0)
                                            registro.setColonia(t_colonia.getText());
                                        if(t_cp.getText().compareTo("")!=0)
                                            registro.setCp(t_cp.getText());
                                        if(t_poblacion.getText().compareTo("")!=0)
                                            registro.setPoblacion(t_poblacion.getText());
                                        registro.setEstado(t_estado.getSelectedItem().toString());
                                        if(t_rfc.getText().compareTo("")!=0)
                                        {
                                            t_rfc.setText(t_rfc.getText().trim());
                                            registro.setRfc(t_rfc.getText());
                                        }
                                        if(t_telefono1.getText().compareTo("")!=0)
                                            registro.setTel1(t_telefono1.getText());
                                        if(t_telefono2.getText().compareTo("")!=0)
                                            registro.setTel2(t_telefono2.getText());
                                        if(t_fax.getText().compareTo("")!=0)
                                            registro.setFax(t_fax.getText());                                        
                                        if(t_email.getText().compareTo("")!=0)
                                            registro.setEmail(t_email.getText());
                                        if(t_representante.getText().compareTo("")!=0)
                                            registro.setRepresentante(t_representante.getText());
                                        if(t_cuenta.getText().compareTo("")!=0)
                                            registro.setCta(t_cuenta.getText());
                                        if(t_credito_limite.getText().compareTo("")!=0)
                                            registro.setCredLimite(Float.parseFloat(t_credito_limite.getText()));
                                        if(t_credito_plazo.getText().compareTo("")!=0)
                                            registro.setCredPlazo(Integer.parseInt(t_credito_plazo.getText()));
                                        if(t_credito_descuento.getText().compareTo("")!=0)
                                            registro.setCredDescuento(Float.parseFloat(t_credito_descuento.getText()));
                                        if(t_tiempo_entrega.getText().compareTo("")!=0)
                                            registro.setTiempoEntrega(Integer.parseInt(t_tiempo_entrega.getText()));
                                        if(t_importe_compras.getText().compareTo("")!=0)
                                            registro.setImpCompras(Float.parseFloat(t_importe_compras.getText()));    
                                        if(t_giro.getText().compareTo("")!=0)
                                            registro.setGiro(t_giro.getText());
                                        if(t_notas.getText().compareTo("")!=0)
                                            registro.setNotas(t_notas.getText());      
                                        registro.setTipo(t_tipo.getSelectedIndex());
                                        if(checkhoja.isSelected())
                                            registro.setEspHojalateria(true);
                                        else
                                            registro.setEspHojalateria(false);
                                        if(espmeca.isSelected())
                                            registro.setEspMecanica(true);
                                        else
                                            registro.setEspMecanica(false);
                                        if(espsusp.isSelected())
                                            registro.setEspSuspension(true);
                                        else
                                            registro.setEspSuspension(false);                                 
                                        if(espelec.isSelected())
                                            registro.setEspElectricidad(true);
                                        else
                                            registro.setEspElectricidad(false);
                                        if(usuario.getText().compareTo("")!=0)
                                            registro.setUsuario(usuario.getText());
                                        if(password.getText().compareTo("")!=0)
                                            registro.setClave(password.getText());
                                        
                                        Integer respuesta=guardarProveedor(registro);
                                        if(respuesta==null)
                                        {
                                            cajas(true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true);
                                            b_guardar.setEnabled(true);
                                        }
                                        else
                                        {
                                            JOptionPane.showMessageDialog(null, "Registro almacenado con la clave:  " +respuesta);
                                            borra_cajas();
                                            t_nombre.requestFocus();
                                        }
                                    }
                                    else
                                    {
                                        JOptionPane.showMessageDialog(null, "¡El RFC ya existe!");
                                        t_rfc.requestFocus();
                                    }
                                }
                                else
                                {
                                    JOptionPane.showMessageDialog(null, "¡Debe introducir el tipo!");
                                    t_tipo.requestFocus();
                                }
                            }
                            else
                            {
                                JOptionPane.showMessageDialog(null, "¡Debe introducir el imp de compras!");
                                t_importe_compras.requestFocus();
                            }
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(null, "¡Debe introducir el tiempo de entrega!");
                            t_tiempo_entrega.requestFocus();
                        }
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "¡Debe introducir el crédito de descuento!");
                        t_credito_descuento.requestFocus();
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "¡Debe introducir el crédito plazo!");
                    t_credito_plazo.requestFocus();
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "¡Debe introducir el RFC del proveedor!");
                t_rfc.requestFocus();
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "¡Debe introducir el nombre del proveedor!");
            t_nombre.requestFocus();
        }
    }//GEN-LAST:event_b_guardarActionPerformed

    private void t_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_nombreKeyTyped
        char car = evt.getKeyChar();
        evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
        if(t_nombre.getText().length()>=150) 
            evt.consume();
    }//GEN-LAST:event_t_nombreKeyTyped

    private void t_direccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_direccionKeyTyped
        char car = evt.getKeyChar();
        evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
        if(t_direccion.getText().length()>=250) 
            evt.consume();
    }//GEN-LAST:event_t_direccionKeyTyped

    private void t_poblacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_poblacionKeyTyped
        char car = evt.getKeyChar();
        evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
        if(t_poblacion.getText().length()>=150) 
            evt.consume();
    }//GEN-LAST:event_t_poblacionKeyTyped

    private void t_rfcKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_rfcKeyTyped
        char car = evt.getKeyChar();
        evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
        if(t_rfc.getText().length()>=13) 
            evt.consume();
    }//GEN-LAST:event_t_rfcKeyTyped

    private void t_telefono2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_telefono2KeyTyped
        char car = evt.getKeyChar();
        if(t_telefono2.getText().length()>=13) 
            evt.consume();
        if((car<'0' || car>'9')) 
            evt.consume();
    }//GEN-LAST:event_t_telefono2KeyTyped

    private void t_faxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_faxKeyTyped
        char car = evt.getKeyChar();
        if(t_fax.getText().length()>=13) 
            evt.consume();
        if((car<'0' || car>'9')) 
            evt.consume();
    }//GEN-LAST:event_t_faxKeyTyped

    private void t_cpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_cpKeyTyped
        char car = evt.getKeyChar();
        if(t_cp.getText().length()>=5) 
            evt.consume();
        if((car<'0' || car>'9')) 
            evt.consume();
    }//GEN-LAST:event_t_cpKeyTyped

    private void t_emailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_emailKeyTyped
        if(t_email.getText().length()>=100) 
            evt.consume();
    }//GEN-LAST:event_t_emailKeyTyped

    private void t_representanteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_representanteKeyTyped
        evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
        if(t_representante.getText().length()>=150) 
            evt.consume();
    }//GEN-LAST:event_t_representanteKeyTyped

    private void t_cuentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_cuentaKeyTyped
        evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
        if(t_cuenta.getText().length()>=10) 
            evt.consume();
    }//GEN-LAST:event_t_cuentaKeyTyped

    private void t_notasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_notasKeyTyped
        evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
        if(t_notas.getText().length()>=250) 
            evt.consume();
    }//GEN-LAST:event_t_notasKeyTyped

    private void t_telefono1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_telefono1KeyTyped
        char car = evt.getKeyChar();
        if(t_telefono1.getText().length()>=13) 
            evt.consume();
        if((car<'0' || car>'9')) 
            evt.consume();
    }//GEN-LAST:event_t_telefono1KeyTyped

    private void t_coloniaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_coloniaKeyTyped
        char car = evt.getKeyChar();
        evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
        if(t_colonia.getText().length()>=150) 
            evt.consume();
    }//GEN-LAST:event_t_coloniaKeyTyped

    private void t_giroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_giroKeyTyped
        char car = evt.getKeyChar();
        evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
        if(t_giro.getText().length()>=150)
        evt.consume();
    }//GEN-LAST:event_t_giroKeyTyped

    private void t_credito_descuentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_credito_descuentoKeyTyped
        char car = evt.getKeyChar();
        //if(t_credito_descuento.getText().length()>=9)
        //evt.consume();
        if((car<'0' && car!='.') || (car>'9' && car!='.'))
        evt.consume();
    }//GEN-LAST:event_t_credito_descuentoKeyTyped

    private void t_credito_descuentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_credito_descuentoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_t_credito_descuentoFocusLost

    private void t_importe_comprasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_importe_comprasKeyTyped
        char car = evt.getKeyChar();
        //if(t_importe_compras.getText().length()>=9)
        //evt.consume();
        if((car<'0' && car!='.') || (car>'9' && car!='.'))
        evt.consume();
    }//GEN-LAST:event_t_importe_comprasKeyTyped

    private void t_importe_comprasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_importe_comprasFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_t_importe_comprasFocusLost

    private void t_credito_plazoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_credito_plazoKeyTyped
        char car = evt.getKeyChar();
        //if(t_credito_plazo.getText().length()>=4)
        //evt.consume();
        if((car<'0' || car>'9'))
        evt.consume();
    }//GEN-LAST:event_t_credito_plazoKeyTyped

    private void t_tiempo_entregaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_tiempo_entregaKeyTyped
        char car = evt.getKeyChar();
        //if(t_tiempo_entrega.getText().length()>=4)
        //  evt.consume();
        if((car<'0' || car>'9'))
        evt.consume();
    }//GEN-LAST:event_t_tiempo_entregaKeyTyped

    private void t_credito_limiteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_credito_limiteKeyTyped
        char car = evt.getKeyChar();
        //if(t_credito_limite.getText().length()>=9)
        //evt.consume();
        if((car<'0' && car!='.') || (car>'9' && car!='.'))
        evt.consume();
    }//GEN-LAST:event_t_credito_limiteKeyTyped

    private void cuenta_coiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cuenta_coiKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_cuenta_coiKeyTyped

    private void cuenta_conceptoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cuenta_conceptoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_cuenta_conceptoKeyTyped
    private Usuario actor=null; 
    private void coiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coiActionPerformed
        // TODO add your handling code here:
         try{
            buscaCuentas obj1 = new buscaCuentas(new javax.swing.JFrame(), true, sessionPrograma,actor, " and id_cuentas like '%2110%'");
            Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
            obj1.setLocation((d.width/2)-(obj1.getWidth()/2), (d.height/2)-(obj1.getHeight()/2));
            obj1.setVisible(true);
            ArrayList lista=obj1.getReturnStatus();
            cuenta_coi.setText(lista.get(0).toString());
           }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_coiActionPerformed

    private void cpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpActionPerformed
        // TODO add your handling code here:
        try{
            buscaCuentas obj1 = new buscaCuentas(new javax.swing.JFrame(), true, sessionPrograma, actor, "");
            Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
            obj1.setLocation((d.width/2)-(obj1.getWidth()/2), (d.height/2)-(obj1.getHeight()/2));
            obj1.setVisible(true);
            ArrayList listar=obj1.getReturnStatus();
            cuenta_concepto.setText(listar.get(0).toString());
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_cpActionPerformed

    private void usuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usuarioKeyTyped
        // TODO add your handling code here:
        evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
        if(usuario.getText().length()>=10){
            evt.consume();
        }
    }//GEN-LAST:event_usuarioKeyTyped

    private void passwordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyTyped
        // TODO add your handling code here:
        evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
        if(password.getText().length()>=10){
            evt.consume();
        }
    }//GEN-LAST:event_passwordKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        buscaUsoCfdi obj = new buscaUsoCfdi(new javax.swing.JFrame(), true, this.sessionPrograma, this.user);
        obj.t_busca.requestFocus();
        obj.formatoTabla();
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        obj.setLocation((d.width/2)-(obj.getWidth()/2), (d.height/2)-(obj.getHeight()/2));
        obj.setVisible(true);

        UsoCfdi actor=obj.getReturnStatus();
        if(actor!=null)
        {
            t_id_cfdi.setText(actor.getIdUsoCfdi());
            t_descripcion_cfdi.setText(actor.getDescripcion());
        }
        else
        {
            t_id_cfdi.setText("");
            t_descripcion_cfdi.setText("");
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_cancelar;
    private javax.swing.JButton b_guardar;
    private javax.swing.JCheckBox checkhoja;
    private javax.swing.JButton coi;
    private javax.swing.JButton cp;
    private javax.swing.JTextField cuenta_coi;
    private javax.swing.JTextField cuenta_concepto;
    private javax.swing.JCheckBox espelec;
    private javax.swing.JCheckBox espmeca;
    private javax.swing.JCheckBox espsusp;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel l_colonia;
    private javax.swing.JLabel l_cp;
    private javax.swing.JLabel l_credito_descuento;
    private javax.swing.JLabel l_credito_limite;
    private javax.swing.JLabel l_credito_plazo;
    private javax.swing.JLabel l_direccion;
    private javax.swing.JLabel l_email;
    private javax.swing.JLabel l_estado;
    private javax.swing.JLabel l_fax;
    private javax.swing.JLabel l_giro;
    private javax.swing.JLabel l_importe_compras;
    private javax.swing.JLabel l_importe_compras1;
    private javax.swing.JLabel l_importe_compras2;
    private javax.swing.JLabel l_importe_compras3;
    private javax.swing.JLabel l_nombre;
    private javax.swing.JLabel l_poblacion;
    private javax.swing.JLabel l_puesto1;
    private javax.swing.JLabel l_representante1;
    private javax.swing.JLabel l_rfc;
    private javax.swing.JLabel l_telefono1;
    private javax.swing.JLabel l_telefono2;
    private javax.swing.JLabel l_tiempo_entrega;
    private javax.swing.JLabel l_tipo;
    private javax.swing.JLabel l_tipo1;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField t_colonia;
    private javax.swing.JTextField t_cp;
    private javax.swing.JTextField t_credito_descuento;
    private javax.swing.JTextField t_credito_limite;
    private javax.swing.JTextField t_credito_plazo;
    private javax.swing.JTextField t_cuenta;
    private javax.swing.JTextField t_descripcion_cfdi;
    private javax.swing.JTextField t_direccion;
    private javax.swing.JTextField t_email;
    private javax.swing.JComboBox t_estado;
    private javax.swing.JTextField t_fax;
    private javax.swing.JTextField t_giro;
    private javax.swing.JTextField t_id_cfdi;
    private javax.swing.JTextField t_importe_compras;
    private javax.swing.JTextField t_nombre;
    private javax.swing.JTextArea t_notas;
    private javax.swing.JTextField t_poblacion;
    private javax.swing.JTextField t_representante;
    private javax.swing.JTextField t_rfc;
    private javax.swing.JTextField t_telefono1;
    private javax.swing.JTextField t_telefono2;
    private javax.swing.JTextField t_tiempo_entrega;
    private javax.swing.JComboBox t_tipo;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables

    private List<Object[]> executeHQLQuery(String hql) 
    {
        try {
            Session session = HibernateUtil.getSessionFactory().openSession();
            session.beginTransaction();
            Query q = session.createQuery(hql);
            List resultList = q.list();
            session.getTransaction().commit();
            session.disconnect();
            return resultList;
        } catch (HibernateException he) {
            he.printStackTrace();
            List lista= null;
            return lista;
        }
    }
    private Integer guardarProveedor(Proveedor obj) 
    {
        Session session = HibernateUtil.getSessionFactory().openSession();
        Integer IdProveedor = null;
        try 
        {
            session.beginTransaction();
            if(cuenta_coi.getText().compareTo("")!=0){
                Cuentas cuen = (Cuentas)session.get(Cuentas.class, cuenta_coi.getText());
                obj.setCuentasByCtaProv(cuen);
            }
            if(cuenta_concepto.getText().compareTo("")!=0){
                Cuentas conp = (Cuentas)session.get(Cuentas.class, cuenta_concepto.getText());
                obj.setCuentasByCtaGasto(conp);
            }
            if(t_id_cfdi.getText().compareTo("")!=0)
            { 
                UsoCfdi uso=(UsoCfdi) session.createCriteria(UsoCfdi.class).add(Restrictions.eq("idUsoCfdi", t_id_cfdi.getText())).setMaxResults(1).uniqueResult();
                obj.setUsoCfdi(uso);
            }
            IdProveedor=(Integer) session.save(obj);
            session.save(obj);
            session.getTransaction().commit();
            return null;
        } 
        catch (HibernateException he) 
        {
            he.printStackTrace();
            session.getTransaction().rollback();
            return null;
        }
        finally
        {
            session.close();
            return IdProveedor;
        }
    }
    public boolean consultaProveedor(String rfc)
    {
        List <Object[]> resultList=executeHQLQuery("from Proveedor obj where obj.rfc='"+rfc+"'");
        if(resultList.size()>0)
            return true;
        else
            return false;
    }
    private void cajas( boolean nombre, boolean direccion, boolean colonia, boolean cp, boolean poblacion, boolean estado, boolean rfc, boolean tel1, boolean tel2, boolean fax, boolean email, boolean representante, boolean cuenta, boolean credlim, boolean credplazo, boolean creddesc, boolean tiempoent, boolean impcom, boolean giro, boolean notas, boolean tipo)
    {   
        t_nombre.setEnabled(nombre);
        t_direccion.setEnabled(direccion);
        t_colonia.setEnabled(colonia);
        t_cp.setEnabled(cp);
        t_poblacion.setEnabled(poblacion);
        t_estado.setEnabled(estado);
        t_rfc.setEnabled(rfc);
        t_telefono1.setEnabled(tel1);
        t_telefono2.setEnabled(tel2);
        t_fax.setEnabled(fax);
        t_email.setEnabled(email);
        t_representante.setEnabled(representante);
        t_cuenta.setEnabled(cuenta);
        t_credito_limite.setEnabled(credlim);
        t_credito_plazo.setEnabled(credplazo);
        t_credito_descuento.setEnabled(creddesc);
        t_tiempo_entrega.setEnabled(tiempoent);
        t_importe_compras.setEnabled(impcom);
        t_giro.setEnabled(giro);
        t_notas.setEnabled(notas);
        t_tipo.setEnabled(tipo);
    }
    private void borra_cajas()
    {
        t_nombre.setText("");
        t_direccion.setText("");
        t_colonia.setText("");
        t_cp.setText("");
        t_poblacion.setText("");
        t_rfc.setText("");
        t_telefono1.setText("");
        t_telefono2.setText("");
        t_fax.setText("");
        t_email.setText("");
        t_representante.setText("");
        t_cuenta.setText("");
        t_credito_limite.setText("");
        t_credito_plazo.setText("");
        t_credito_descuento.setText("");
        t_tiempo_entrega.setText("");
        t_importe_compras.setText("");
        t_giro.setText("");
        t_notas.setText("");     
        checkhoja.setSelected(false);
        espmeca.setSelected(false);
        espsusp.setSelected(false);
        espelec.setSelected(false);
        cuenta_coi.setText("");
        cuenta_concepto.setText("");
        t_id_cfdi.setText("");
        t_descripcion_cfdi.setText("");
    }
}