package Hibernate.entidades;
// Generated 10/12/2016 11:06:21 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Agente generated by hbm2java
 */
public class Agente  implements java.io.Serializable {


     private Integer idAgente;
     private String nombre;
     private Set ordens = new HashSet(0);

    public Agente() {
    }

    public Agente(String nombre, Set ordens) {
       this.nombre = nombre;
       this.ordens = ordens;
    }
   
    public Integer getIdAgente() {
        return this.idAgente;
    }
    
    public void setIdAgente(Integer idAgente) {
        this.idAgente = idAgente;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getOrdens() {
        return this.ordens;
    }
    
    public void setOrdens(Set ordens) {
        this.ordens = ordens;
    }




}


