package Hibernate.entidades;
// Generated 10/12/2016 11:06:21 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Ajustador generated by hbm2java
 */
public class Ajustador  implements java.io.Serializable {


     private Integer idAjustador;
     private String nombre;
     private Set ordens = new HashSet(0);

    public Ajustador() {
    }

    public Ajustador(String nombre, Set ordens) {
       this.nombre = nombre;
       this.ordens = ordens;
    }
   
    public Integer getIdAjustador() {
        return this.idAjustador;
    }
    
    public void setIdAjustador(Integer idAjustador) {
        this.idAjustador = idAjustador;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getOrdens() {
        return this.ordens;
    }
    
    public void setOrdens(Set ordens) {
        this.ordens = ordens;
    }




}


