package Hibernate.entidades;
// Generated 29/11/2017 10:51:29 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Avance generated by hbm2java
 */
public class Avance  implements java.io.Serializable {


     private Integer idAvance;
     private Orden orden;
     private Date fechaEnvio;
     private String comentario;
     private String idUsuario;
     private Byte visto;
     private Date fechaVisto;

    public Avance() {
    }

    public Avance(Orden orden, Date fechaEnvio, String comentario, String idUsuario, Byte visto, Date fechaVisto) {
       this.orden = orden;
       this.fechaEnvio = fechaEnvio;
       this.comentario = comentario;
       this.idUsuario = idUsuario;
       this.visto = visto;
       this.fechaVisto = fechaVisto;
    }
   
    public Integer getIdAvance() {
        return this.idAvance;
    }
    
    public void setIdAvance(Integer idAvance) {
        this.idAvance = idAvance;
    }
    public Orden getOrden() {
        return this.orden;
    }
    
    public void setOrden(Orden orden) {
        this.orden = orden;
    }
    public Date getFechaEnvio() {
        return this.fechaEnvio;
    }
    
    public void setFechaEnvio(Date fechaEnvio) {
        this.fechaEnvio = fechaEnvio;
    }
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }
    public String getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(String idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Byte getVisto() {
        return this.visto;
    }
    
    public void setVisto(Byte visto) {
        this.visto = visto;
    }
    public Date getFechaVisto() {
        return this.fechaVisto;
    }
    
    public void setFechaVisto(Date fechaVisto) {
        this.fechaVisto = fechaVisto;
    }




}


