package Hibernate.entidades;
// Generated 13/02/2017 09:18:03 AM by Hibernate Tools 3.6.0



/**
 * Consumible generated by hbm2java
 */
public class Consumible  implements java.io.Serializable {


     private int idConsumible;
     private Ejemplar ejemplar;
     private Orden orden;
     private String medida;
     private double cantidad;
     private double precio;
     private boolean espHoj;
     private boolean espMec;
     private boolean espSus;
     private boolean espEle;
     private boolean espPin;
     private String tipo;

    public Consumible() {
    }

	
    public Consumible(int idConsumible, double cantidad, double precio, boolean espHoj, boolean espMec, boolean espSus, boolean espEle, boolean espPin) {
        this.idConsumible = idConsumible;
        this.cantidad = cantidad;
        this.precio = precio;
        this.espHoj = espHoj;
        this.espMec = espMec;
        this.espSus = espSus;
        this.espEle = espEle;
        this.espPin = espPin;
    }
    public Consumible(int idConsumible, Ejemplar ejemplar, Orden orden, String medida, double cantidad, double precio, boolean espHoj, boolean espMec, boolean espSus, boolean espEle, boolean espPin, String tipo) {
       this.idConsumible = idConsumible;
       this.ejemplar = ejemplar;
       this.orden = orden;
       this.medida = medida;
       this.cantidad = cantidad;
       this.precio = precio;
       this.espHoj = espHoj;
       this.espMec = espMec;
       this.espSus = espSus;
       this.espEle = espEle;
       this.espPin = espPin;
       this.tipo = tipo;
    }
   
    public int getIdConsumible() {
        return this.idConsumible;
    }
    
    public void setIdConsumible(int idConsumible) {
        this.idConsumible = idConsumible;
    }
    public Ejemplar getEjemplar() {
        return this.ejemplar;
    }
    
    public void setEjemplar(Ejemplar ejemplar) {
        this.ejemplar = ejemplar;
    }
    public Orden getOrden() {
        return this.orden;
    }
    
    public void setOrden(Orden orden) {
        this.orden = orden;
    }
    public String getMedida() {
        return this.medida;
    }
    
    public void setMedida(String medida) {
        this.medida = medida;
    }
    public double getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(double cantidad) {
        this.cantidad = cantidad;
    }
    public double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(double precio) {
        this.precio = precio;
    }
    public boolean isEspHoj() {
        return this.espHoj;
    }
    
    public void setEspHoj(boolean espHoj) {
        this.espHoj = espHoj;
    }
    public boolean isEspMec() {
        return this.espMec;
    }
    
    public void setEspMec(boolean espMec) {
        this.espMec = espMec;
    }
    public boolean isEspSus() {
        return this.espSus;
    }
    
    public void setEspSus(boolean espSus) {
        this.espSus = espSus;
    }
    public boolean isEspEle() {
        return this.espEle;
    }
    
    public void setEspEle(boolean espEle) {
        this.espEle = espEle;
    }
    public boolean isEspPin() {
        return this.espPin;
    }
    
    public void setEspPin(boolean espPin) {
        this.espPin = espPin;
    }

    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }


}


