package Hibernate.entidades;
// Generated 29/11/2017 10:51:29 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * CuentaSeguimiento generated by hbm2java
 */
public class CuentaSeguimiento  implements java.io.Serializable {


     private Integer idCuentaSeguimiento;
     private Proveedor proveedor;
     private String email;
     private String clave;
     private Date fecha;
     private String token;
     private String usuario;

    public CuentaSeguimiento() {
    }

    public CuentaSeguimiento(Proveedor proveedor, String email, String clave, Date fecha, String token, String usuario) {
       this.proveedor = proveedor;
       this.email = email;
       this.clave = clave;
       this.fecha = fecha;
       this.token = token;
       this.usuario = usuario;
    }
   
    public Integer getIdCuentaSeguimiento() {
        return this.idCuentaSeguimiento;
    }
    
    public void setIdCuentaSeguimiento(Integer idCuentaSeguimiento) {
        this.idCuentaSeguimiento = idCuentaSeguimiento;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getToken() {
        return this.token;
    }
    
    public void setToken(String token) {
        this.token = token;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }




}


