package Hibernate.entidades;
// Generated 13/07/2016 09:31:27 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Destajo generated by hbm2java
 */
public class Destajo  implements java.io.Serializable {


     private int idDestajo;
     private Orden orden;
     private Usuario usuario;
     private Date fechaDestajo;
     private Double avance;
     private Double horas;
     private Double importe;
     private String notas;
     private String especialidad;
     private Date fechaModifico;

    public Destajo() {
    }

	
    public Destajo(int idDestajo, Orden orden, String especialidad) {
        this.idDestajo = idDestajo;
        this.orden = orden;
        this.especialidad = especialidad;
    }
    public Destajo(int idDestajo, Orden orden, Usuario usuario, Date fechaDestajo, Double avance, Double horas, Double importe, String notas, String especialidad, Date fechaModifico) {
       this.idDestajo = idDestajo;
       this.orden = orden;
       this.usuario = usuario;
       this.fechaDestajo = fechaDestajo;
       this.avance = avance;
       this.horas = horas;
       this.importe = importe;
       this.notas = notas;
       this.especialidad = especialidad;
       this.fechaModifico = fechaModifico;
    }
   
    public int getIdDestajo() {
        return this.idDestajo;
    }
    
    public void setIdDestajo(int idDestajo) {
        this.idDestajo = idDestajo;
    }
    public Orden getOrden() {
        return this.orden;
    }
    
    public void setOrden(Orden orden) {
        this.orden = orden;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFechaDestajo() {
        return this.fechaDestajo;
    }
    
    public void setFechaDestajo(Date fechaDestajo) {
        this.fechaDestajo = fechaDestajo;
    }
    public Double getAvance() {
        return this.avance;
    }
    
    public void setAvance(Double avance) {
        this.avance = avance;
    }
    public Double getHoras() {
        return this.horas;
    }
    
    public void setHoras(Double horas) {
        this.horas = horas;
    }
    public String getNotas() {
        return this.notas;
    }
    public Double getImporte() {
        return this.importe;
    }
    
    public void setImporte(Double importe) {
        this.importe = importe;
    }
    
    public void setNotas(String notas) {
        this.notas = notas;
    }
    public String getEspecialidad() {
        return this.especialidad;
    }
    
    public void setEspecialidad(String especialidad) {
        this.especialidad = especialidad;
    }
    public Date getFechaModifico() {
        return this.fechaModifico;
    }
    
    public void setFechaModifico(Date fechaModifico) {
        this.fechaModifico = fechaModifico;
    }




}


