package Hibernate.entidades;
// Generated 13/02/2018 11:12:16 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * HistorialFecha generated by hbm2java
 */
public class HistorialFecha  implements java.io.Serializable {


     private Integer idHistorial;
     private Orden orden;
     private Usuario usuario;
     private Date fecha;
     private String atributo;
     private Date fechaModificacion;

    public HistorialFecha() {
    }

    public HistorialFecha(Orden orden, Usuario usuario, Date fecha, String atributo, Date fechaModificacion) {
       this.orden = orden;
       this.usuario = usuario;
       this.fecha = fecha;
       this.atributo = atributo;
       this.fechaModificacion = fechaModificacion;
    }
   
    public Integer getIdHistorial() {
        return this.idHistorial;
    }
    
    public void setIdHistorial(Integer idHistorial) {
        this.idHistorial = idHistorial;
    }
    public Orden getOrden() {
        return this.orden;
    }
    
    public void setOrden(Orden orden) {
        this.orden = orden;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getAtributo() {
        return this.atributo;
    }
    
    public void setAtributo(String atributo) {
        this.atributo = atributo;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }




}


