package Hibernate.entidades;
// Generated 10/12/2016 11:06:21 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Notificacion generated by hbm2java
 */
public class Notificacion  implements java.io.Serializable {


     private Integer idNotificacion;
     private Acceso acceso;
     private String mensaje;
     private String extra;
     private Integer intentos;
     private Boolean visto;
     private Date fechaVisto;

    public Notificacion() {
    }

	
    public Notificacion(Boolean visto) {
        this.visto = visto;
    }
    public Notificacion(Acceso acceso, String mensaje, String extra, Integer intentos, Boolean visto, Date fechaVisto) {
       this.acceso = acceso;
       this.mensaje = mensaje;
       this.extra = extra;
       this.intentos = intentos;
       this.visto = visto;
       this.fechaVisto = fechaVisto;
    }
   
    public Integer getIdNotificacion() {
        return this.idNotificacion;
    }
    
    public void setIdNotificacion(Integer idNotificacion) {
        this.idNotificacion = idNotificacion;
    }
    public Acceso getAcceso() {
        return this.acceso;
    }
    
    public void setAcceso(Acceso acceso) {
        this.acceso = acceso;
    }
    public String getMensaje() {
        return this.mensaje;
    }
    
    public void setMensaje(String mensaje) {
        this.mensaje = mensaje;
    }
    public String getExtra() {
        return this.extra;
    }
    
    public void setExtra(String extra) {
        this.extra = extra;
    }
    public Integer getIntentos() {
        return this.intentos;
    }
    
    public void setIntentos(Integer intentos) {
        this.intentos = intentos;
    }
    public Boolean getVisto() {
        return this.visto;
    }
    
    public void setVisto(Boolean visto) {
        this.visto = visto;
    }
    public Date getFechaVisto() {
        return this.fechaVisto;
    }
    
    public void setFechaVisto(Date fechaVisto) {
        this.fechaVisto = fechaVisto;
    }




}


