package Hibernate.entidades;
// Generated 21/12/2016 12:54:15 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PagoAdicional generated by hbm2java
 */
public class PagoAdicional  implements java.io.Serializable {


     private Integer idPagoAdicional;
     private TrabajoExtra trabajoExtra;
     private Date fecha;
     private Double porcentaje;
     private Double impote;
     private String nota;
     private Double total;
     private Set almacens = new HashSet(0);

    public PagoAdicional() {
    }

    public PagoAdicional(TrabajoExtra trabajoExtra, Date fecha, Double porcentaje, Double impote, String nota, Double total, Set almacens) {
       this.trabajoExtra = trabajoExtra;
       this.fecha = fecha;
       this.porcentaje = porcentaje;
       this.impote = impote;
       this.nota = nota;
       this.total = total;
       this.almacens = almacens;
    }
   
    public Integer getIdPagoAdicional() {
        return this.idPagoAdicional;
    }
    
    public void setIdPagoAdicional(Integer idPagoAdicional) {
        this.idPagoAdicional = idPagoAdicional;
    }
    public TrabajoExtra getTrabajoExtra() {
        return this.trabajoExtra;
    }
    
    public void setTrabajoExtra(TrabajoExtra trabajoExtra) {
        this.trabajoExtra = trabajoExtra;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Double getPorcentaje() {
        return this.porcentaje;
    }
    
    public void setPorcentaje(Double porcentaje) {
        this.porcentaje = porcentaje;
    }
    public Double getImpote() {
        return this.impote;
    }
    
    public void setImpote(Double impote) {
        this.impote = impote;
    }
    public String getNota() {
        return this.nota;
    }
    
    public void setNota(String nota) {
        this.nota = nota;
    }
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }
    public Set getAlmacens() {
        return this.almacens;
    }
    
    public void setAlmacens(Set almacens) {
        this.almacens = almacens;
    }




}


