package Hibernate.entidades;
// Generated 25/09/2017 04:58:22 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ProductoServicio generated by hbm2java
 */
public class ProductoServicio  implements java.io.Serializable {


     private String idProductoServicio;
     private String descripcion;
     private Date fechaInicioVigencia;
     private Date fechaFinVigencia;
     private Set conceptos = new HashSet(0);

    public ProductoServicio() {
    }

	
    public ProductoServicio(String idProductoServicio) {
        this.idProductoServicio = idProductoServicio;
    }
    public ProductoServicio(String idProductoServicio, String descripcion, Date fechaInicioVigencia, Date fechaFinVigencia, Set conceptos) {
       this.idProductoServicio = idProductoServicio;
       this.descripcion = descripcion;
       this.fechaInicioVigencia = fechaInicioVigencia;
       this.fechaFinVigencia = fechaFinVigencia;
       this.conceptos = conceptos;
    }
   
    public String getIdProductoServicio() {
        return this.idProductoServicio;
    }
    
    public void setIdProductoServicio(String idProductoServicio) {
        this.idProductoServicio = idProductoServicio;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFechaInicioVigencia() {
        return this.fechaInicioVigencia;
    }
    
    public void setFechaInicioVigencia(Date fechaInicioVigencia) {
        this.fechaInicioVigencia = fechaInicioVigencia;
    }
    public Date getFechaFinVigencia() {
        return this.fechaFinVigencia;
    }
    
    public void setFechaFinVigencia(Date fechaFinVigencia) {
        this.fechaFinVigencia = fechaFinVigencia;
    }
    public Set getConceptos() {
        return this.conceptos;
    }
    
    public void setConceptos(Set conceptos) {
        this.conceptos = conceptos;
    }




}


