package Hibernate.entidades;
// Generated 23/10/2015 08:59:16 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Servicio generated by hbm2java
 */
public class Servicio  implements java.io.Serializable {


     private String idServicio;
     private String descripcion;
     private Set items = new HashSet(0);
     private Set ordenes = new HashSet(0);

    public Servicio() {
    }

	
    public Servicio(String idServicio) {
        this.idServicio = idServicio;
    }
    public Servicio(String idServicio, String descripcion, Set items, Set ordenes) {
       this.idServicio = idServicio;
       this.descripcion = descripcion;
       this.items = items;
       this.ordenes = ordenes;
    }
   
    public String getIdServicio() {
        return this.idServicio;
    }
    
    public void setIdServicio(String idServicio) {
        this.idServicio = idServicio;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    
    public Set getItems() {
        return this.items;
    }
    
    public void setItems(Set items) {
        this.items = items;
    }

    public Set getOrdenes() {
        return this.ordenes;
    }
    
    public void setOrdenes(Set ordenes) {
        this.ordenes = ordenes;
    }



}


