package Hibernate.entidades;
// Generated 13/07/2016 09:31:27 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Destajo generated by hbm2java
 */
public class TrabajoExtra  implements java.io.Serializable {


     private int idAdicional;
     private Orden orden;
     private Empleado empleado;
     private Date fechaDestajo;
     private Double horas;
     private Double importe;
     private String notas;
     private Boolean autorizado;
     private Usuario usuario;

    public TrabajoExtra() {
    }

	
    public TrabajoExtra(int idAdicional) {
        this.idAdicional = idAdicional;
    }
    public TrabajoExtra(int idAdicional, Orden orden, Empleado empleado, Date fechaDestajo, Double horas, Double importe, String notas, Boolean autorizado, Usuario usuario) {
       this.idAdicional = idAdicional;
       this.orden = orden;
       this.empleado = empleado;
       this.fechaDestajo = fechaDestajo;
       this.horas = horas;
       this.importe = importe;
       this.notas = notas;
       this.autorizado = autorizado;
       this.usuario = usuario;
    }
   
    public int getIdAdicional() {
        return this.idAdicional;
    }
    
    public void setIdAdicional(int idAdicional) {
        this.idAdicional = idAdicional;
    }
    public Orden getOrden() {
        return this.orden;
    }
    
    public void setOrden(Orden orden) {
        this.orden = orden;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Date getFechaDestajo() {
        return this.fechaDestajo;
    }
    
    public void setFechaDestajo(Date fechaDestajo) {
        this.fechaDestajo = fechaDestajo;
    }
  
    public Double getHoras() {
        return this.horas;
    }
    
    public void setHoras(Double horas) {
        this.horas = horas;
    }
    public String getNotas() {
        return this.notas;
    }
    public Double getImporte() {
        return this.importe;
    }
    
    public void setImporte(Double importe) {
        this.importe = importe;
    }
    
    public void setNotas(String notas) {
        this.notas = notas;
    }
    public void setAutorizado(Boolean autorizado) {
        this.autorizado = autorizado;
    }
    public Boolean getAutorizado() {
        return this.autorizado;
    }
    
    public Usuario getUsuario(){
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
}


