package Hibernate.entidades;
// Generated 25/09/2017 04:58:22 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UsoCfdi generated by hbm2java
 */
public class UsoCfdi  implements java.io.Serializable {


     private String idUsoCfdi;
     private String descripcion;
     private String fisica;
     private String moral;
     private Date fechaInicioVigencia;
     private Date fechaFinVigencia;
     private Set clienteses = new HashSet(0);
     private Set companias = new HashSet(0);
     private Set proveedors = new HashSet(0);
     private Set pagos = new HashSet(0);

    public UsoCfdi() {
    }

	
    public UsoCfdi(String idUsoCfdi) {
        this.idUsoCfdi = idUsoCfdi;
    }
    public UsoCfdi(String idUsoCfdi, String descripcion, String fisica, String moral, Date fechaInicioVigencia, Date fechaFinVigencia, Set clienteses, Set companias, Set proveedors, Set pagos) {
       this.idUsoCfdi = idUsoCfdi;
       this.descripcion = descripcion;
       this.fisica = fisica;
       this.moral = moral;
       this.fechaInicioVigencia = fechaInicioVigencia;
       this.fechaFinVigencia = fechaFinVigencia;
       this.clienteses = clienteses;
       this.companias = companias;
       this.proveedors = proveedors;
       this.pagos = pagos;
    }
   
    public String getIdUsoCfdi() {
        return this.idUsoCfdi;
    }
    
    public void setIdUsoCfdi(String idUsoCfdi) {
        this.idUsoCfdi = idUsoCfdi;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getFisica() {
        return this.fisica;
    }
    
    public void setFisica(String fisica) {
        this.fisica = fisica;
    }
    public String getMoral() {
        return this.moral;
    }
    
    public void setMoral(String moral) {
        this.moral = moral;
    }
    public Date getFechaInicioVigencia() {
        return this.fechaInicioVigencia;
    }
    
    public void setFechaInicioVigencia(Date fechaInicioVigencia) {
        this.fechaInicioVigencia = fechaInicioVigencia;
    }
    public Date getFechaFinVigencia() {
        return this.fechaFinVigencia;
    }
    
    public void setFechaFinVigencia(Date fechaFinVigencia) {
        this.fechaFinVigencia = fechaFinVigencia;
    }
    public Set getClienteses() {
        return this.clienteses;
    }
    
    public void setClienteses(Set clienteses) {
        this.clienteses = clienteses;
    }
    public Set getCompanias() {
        return this.companias;
    }
    
    public void setCompanias(Set companias) {
        this.companias = companias;
    }
    public Set getProveedors() {
        return this.proveedors;
    }
    
    public void setProveedors(Set proveedors) {
        this.proveedors = proveedors;
    }

    public Set getPagos() {
        return this.pagos;
    }
    
    public void setPagos(Set pagos) {
        this.pagos = pagos;
    }


}


