/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Valuacion;

import Hibernate.Util.HibernateUtil;
import Hibernate.entidades.Orden;
import Hibernate.entidades.Partida;
import Hibernate.entidades.Usuario;
import Integral.Herramientas;
import Servicios.buscaOrden;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.FileReader;
import java.math.BigDecimal;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.hibernate.Session;

/**
 *
 * @author I.S.C.Salvador
 */
public class Presupuestos extends javax.swing.JDialog {

    private  Usuario usr;
    public Orden orden_act=null;
    Herramientas h;
    String estado="";
    String ruta="";
    String sessionPrograma="";
    int configuracion=1, menu=0;
    /**
     * Creates new form Presupuestos
     */
    public Presupuestos(java.awt.Frame parent, boolean modal, String ses, Usuario usuario, int configuracion, int menu) {
        super(parent, modal);
        sessionPrograma=ses;
        usr=usuario;
        this.configuracion=configuracion;
        this.menu=menu;
        initComponents();
        ruta="";
        try
        {
            FileReader f = new FileReader("config.txt");
            BufferedReader b = new BufferedReader(f);
            if((ruta = b.readLine())==null)
                ruta="";
            b.close();
        }catch(Exception e){e.printStackTrace();}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l_orden = new javax.swing.JLabel();
        t_orden = new javax.swing.JTextField();
        b_buscaro = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        t_vales = new javax.swing.JFormattedTextField();
        jLabel32 = new javax.swing.JLabel();
        t_consumibles = new javax.swing.JFormattedTextField();
        b_ac = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        t_costo_refacciones = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        t_ref_autorizadas_directo = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        t_cia_seguros = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        t_autorizado = new javax.swing.JFormattedTextField();
        t_autorizado1 = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        l_orden.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        l_orden.setText("O. Taller");
        l_orden.setMaximumSize(new java.awt.Dimension(210, 15));
        l_orden.setMinimumSize(new java.awt.Dimension(210, 15));
        l_orden.setPreferredSize(new java.awt.Dimension(210, 15));

        t_orden.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        t_orden.setMinimumSize(new java.awt.Dimension(250, 19));
        t_orden.setName(""); // NOI18N
        t_orden.setPreferredSize(new java.awt.Dimension(250, 19));
        t_orden.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_ordenFocusLost(evt);
            }
        });
        t_orden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_ordenActionPerformed(evt);
            }
        });
        t_orden.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                t_ordenKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_ordenKeyTyped(evt);
            }
        });

        b_buscaro.setBackground(new java.awt.Color(2, 135, 242));
        b_buscaro.setIcon(new ImageIcon("imagenes/buscar.png"));
        b_buscaro.setMnemonic(KeyEvent.VK_F1);
        b_buscaro.setToolTipText("Consultar orden de taller");
        b_buscaro.setMaximumSize(new java.awt.Dimension(32, 8));
        b_buscaro.setMinimumSize(new java.awt.Dimension(32, 8));
        b_buscaro.setPreferredSize(new java.awt.Dimension(32, 8));
        b_buscaro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_buscaroActionPerformed(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel31.setText("P. Compras:");

        t_vales.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        t_vales.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        t_vales.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        t_vales.setText("0.00");
        t_vales.setDisabledTextColor(new java.awt.Color(2, 38, 253));

        jLabel32.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel32.setText("P. Consumible:");

        t_consumibles.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        t_consumibles.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        t_consumibles.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        t_consumibles.setText("0.00");
        t_consumibles.setDisabledTextColor(new java.awt.Color(2, 38, 253));

        b_ac.setText("Guardar");
        b_ac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_acActionPerformed(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Refacciones", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 10))); // NOI18N
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t_costo_refacciones.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        t_costo_refacciones.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        t_costo_refacciones.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        t_costo_refacciones.setText("0.00");
        t_costo_refacciones.setDisabledTextColor(new java.awt.Color(2, 38, 253));
        t_costo_refacciones.setEnabled(false);
        t_costo_refacciones.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        t_costo_refacciones.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_costo_refaccionesFocusGained(evt);
            }
        });
        t_costo_refacciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_costo_refaccionesActionPerformed(evt);
            }
        });
        jPanel6.add(t_costo_refacciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 13, 88, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 9)); // NOI18N
        jLabel3.setText("Cotizado:");
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 16, -1, -1));

        l2.setFont(new java.awt.Font("Arial", 0, 9)); // NOI18N
        l2.setText("Cot. Final:");
        jPanel6.add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 15, -1, -1));

        t_ref_autorizadas_directo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        t_ref_autorizadas_directo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        t_ref_autorizadas_directo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        t_ref_autorizadas_directo.setText("0.00");
        t_ref_autorizadas_directo.setDisabledTextColor(new java.awt.Color(2, 38, 253));
        t_ref_autorizadas_directo.setEnabled(false);
        t_ref_autorizadas_directo.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jPanel6.add(t_ref_autorizadas_directo, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 13, 88, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 9)); // NOI18N
        jLabel5.setText("Cia/Seg:");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 37, -1, -1));

        t_cia_seguros.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        t_cia_seguros.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        t_cia_seguros.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        t_cia_seguros.setText("0.00");
        t_cia_seguros.setDisabledTextColor(new java.awt.Color(2, 38, 253));
        t_cia_seguros.setEnabled(false);
        t_cia_seguros.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jPanel6.add(t_cia_seguros, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 35, 88, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 9)); // NOI18N
        jLabel6.setText("Autorizado:");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 38, -1, -1));

        t_autorizado.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        t_autorizado.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        t_autorizado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        t_autorizado.setText("0.00");
        t_autorizado.setDisabledTextColor(new java.awt.Color(2, 38, 253));
        t_autorizado.setEnabled(false);
        t_autorizado.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jPanel6.add(t_autorizado, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 35, 88, -1));

        t_autorizado1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        t_autorizado1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        t_autorizado1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        t_autorizado1.setText("0.00");
        t_autorizado1.setDisabledTextColor(new java.awt.Color(2, 38, 253));
        t_autorizado1.setEnabled(false);
        t_autorizado1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jPanel6.add(t_autorizado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 35, 88, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 9)); // NOI18N
        jLabel8.setText("Total en Vales");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(l_orden, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_orden, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_buscaro, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(b_ac)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel31)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(t_vales, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel32)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(t_consumibles, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(l_orden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(t_orden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(b_buscaro, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(t_vales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_consumibles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32))
                .addGap(18, 18, 18)
                .addComponent(b_ac)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t_ordenFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_ordenFocusLost
        // TODO add your handling code here:
        Session session = HibernateUtil.getSessionFactory().openSession();
        if(t_orden.getText().compareTo("")!=0)
        {
            try
            {
                session.beginTransaction().begin();
                orden_act = (Orden)session.get(Orden.class, Integer.parseInt(t_orden.getText()));
                if(orden_act!=null)
                {
                    t_orden.setText(""+orden_act.getIdOrden());
                    if(orden_act.getFechaCierre()==null)
                    {
                        h= new Herramientas(usr, menu);
                        h.desbloqueaOrden();
                        String resp=h.estadoOrden(orden_act);
                        if(resp.compareTo("")==0 || resp.compareTo("*bloqueada ok*")==0)
                        {
                            buscaApertura();
                            permisos(true, true, true);
                        }
                        else
                        {
                            buscaApertura();
                            permisos(false, false, false);
                            JOptionPane.showMessageDialog(null, "¡Orden Bloqueada por:"+orden_act.getUsuarioByBloqueada().getIdUsuario());
                        }
                    }
                    else
                    {
                        t_orden.setText(""+orden_act.getIdOrden());
                        buscaApertura();
                        this.t_vales.setEnabled(false);
                        this.t_consumibles.setEnabled(false);
                        this.b_ac.setEnabled(false);
                        JOptionPane.showMessageDialog(null, "¡Orden cerrada!");
                    }
                }
            }catch(Exception e){e.printStackTrace();}
            if(session!=null)
            if(session.isOpen())
            session.close();
        }
        else
        {
            this.t_vales.setEnabled(false);
            this.t_consumibles.setEnabled(false);
            this.b_ac.setEnabled(false);
            h= new Herramientas(usr, 0);
            h.desbloqueaOrden();
            b_buscaro.requestFocus();
        }
    }//GEN-LAST:event_t_ordenFocusLost

    private void t_ordenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_ordenActionPerformed
        // TODO add your handling code here:
        this.b_buscaro.requestFocus();
    }//GEN-LAST:event_t_ordenActionPerformed

    private void t_ordenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_ordenKeyReleased
        // TODO add your handling code here:
        if(t_orden.getText().length()>=6)
        {
            b_buscaro.requestFocus();
        }
    }//GEN-LAST:event_t_ordenKeyReleased

    private void t_ordenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_ordenKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if(t_orden.getSelectedText()!=null)
        t_orden.setText(t_orden.getText().replace(t_orden.getSelectedText(), ""));

        if(t_orden.getText().length()>=6)
        {
            evt.consume();
        }
        if((car<'0' || car>'9'))
        evt.consume();
    }//GEN-LAST:event_t_ordenKeyTyped

    private void b_buscaroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_buscaroActionPerformed
        //h=new Herramientas(usr, 0);
        //h.session(sessionPrograma);
        buscaOrden obj = new buscaOrden(new javax.swing.JFrame(), true, usr,0, configuracion);
        obj.t_busca.requestFocus();
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        obj.setLocation((d.width/2)-(obj.getWidth()/2), (d.height/2)-(obj.getHeight()/2));
        obj.setVisible(true);
        orden_act=obj.getReturnStatus();
        try{
            if(orden_act!=null)
            {
                t_orden.setText(""+orden_act.getIdOrden());
                if(orden_act.getFechaCierre()==null)
                {
                    h= new Herramientas(usr, menu);
                    h.desbloqueaOrden();
                    String resp=h.estadoOrden(orden_act);
                    if(resp.compareTo("")==0 || resp.compareTo("*bloqueada ok*")==0)
                    {
                        buscaApertura();
                        permisos(true, true, true);
                    }
                    else
                    {
                        buscaApertura();
                        permisos(false, false, false);
                        JOptionPane.showMessageDialog(null, "¡Orden Bloqueada por:"+orden_act.getUsuarioByBloqueada().getIdUsuario());
                    }
                }
                else
                {
                    t_orden.setText(""+orden_act.getIdOrden());
                    buscaApertura();
                    permisos(false, false, false);
                    JOptionPane.showMessageDialog(null, "¡Orden cerrada!");
                }
            }
            else
            {
                permisos(false, false, false);
                h= new Herramientas(usr, 0);
                h.desbloqueaOrden();
                b_buscaro.requestFocus();
            }
        }catch(Exception e){e.printStackTrace();}
    }//GEN-LAST:event_b_buscaroActionPerformed

    private void b_acActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_acActionPerformed
        // TODO add your handling code here:
        Herramientas h= new Herramientas(this.usr, this.menu);
        Session session = HibernateUtil.getSessionFactory().openSession();
        try
        {
            session.beginTransaction().begin();
            this.orden_act = (Orden)session.get(Orden.class, orden_act.getIdOrden());

            if(t_vales.getText().compareTo("")!=0)
                orden_act.setVales(((Number)t_vales.getValue()).doubleValue());
            else
                orden_act.setVales(0.0d);

            if(t_consumibles.getText().compareTo("")!=0)
                orden_act.setValesConsumibles(((Number)t_consumibles.getValue()).doubleValue());
            else
                orden_act.setValesConsumibles(0.0d);
            session.update(orden_act);
            session.beginTransaction().commit();
            JOptionPane.showMessageDialog(this, "Los datos han sido almacenados");
        }
        catch(Exception e)
        {
            session.beginTransaction().rollback();
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "No se pudo realizar la actualizacion.");
        }
        if(session!=null)
        if(session.isOpen())
        {
            session.flush();
            session.clear();
            session.close();
        }
    }//GEN-LAST:event_b_acActionPerformed

    private void t_costo_refaccionesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_costo_refaccionesFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_t_costo_refaccionesFocusGained

    private void t_costo_refaccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_costo_refaccionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_costo_refaccionesActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        doClose();
    }//GEN-LAST:event_formWindowClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_ac;
    private javax.swing.JButton b_buscaro;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l_orden;
    private javax.swing.JFormattedTextField t_autorizado;
    private javax.swing.JFormattedTextField t_autorizado1;
    private javax.swing.JFormattedTextField t_cia_seguros;
    private javax.swing.JFormattedTextField t_consumibles;
    private javax.swing.JFormattedTextField t_costo_refacciones;
    public javax.swing.JTextField t_orden;
    private javax.swing.JFormattedTextField t_ref_autorizadas_directo;
    private javax.swing.JFormattedTextField t_vales;
    // End of variables declaration//GEN-END:variables

    private void permisos(boolean vales, boolean consumibles, boolean guardar)
    {
        Session session = HibernateUtil.getSessionFactory().openSession();
        try
        {
            Orden objeto = (Orden)session.get(Orden.class, Integer.parseInt(t_orden.getText()));
            this.usr = (Usuario)session.get(Usuario.class, this.usr.getIdUsuario());

            /*if(this.usr.getRestaurar()==false)
            {*/
                t_vales.setEnabled(vales);
                t_consumibles.setEnabled(consumibles);
                b_ac.setEnabled(guardar);
            /*}
            else
            {
                t_vales.setEnabled(false);
                t_consumibles.setEnabled(false);
                b_ac.setEnabled(false);
            }*/
        }catch(Exception e)
        {
            System.out.println(e);
        }
        if(session!=null)
            if(session.isOpen())
                session.close();
    }
    
    private void buscaApertura()
    {
        Session session = HibernateUtil.getSessionFactory().openSession();
        try
        {
            orden_act= (Orden)session.get(Orden.class, this.orden_act.getIdOrden());
            if(orden_act!=null)
            {
                //cotizado
                Partida[] partidas=(Partida[])orden_act.getPartidasForIdOrden().toArray(new Partida[0]);
                double suma=0.0d;
                for(int p=0; p<partidas.length; p++)
                {
                    suma+=partidas[p].getCU()*partidas[p].getCant();
                }
                BigDecimal conv=new BigDecimal(suma);
                t_costo_refacciones.setValue(conv.setScale(2, BigDecimal.ROUND_HALF_UP).doubleValue());
                
                
                //CIA
                suma=0d;
                for(int p=0; p<partidas.length; p++)
                {
                    suma+=Math.round(partidas[p].getCU()/(1-(partidas[p].getPorcentaje()*0.01)))*partidas[p].getCant();
                }
                conv=new BigDecimal(suma);
                t_cia_seguros.setValue(conv.setScale(2, BigDecimal.ROUND_HALF_UP).doubleValue());

                //Autorizado
                suma = 0d;
                for(int p=0; p<partidas.length; p++)
                {
                    if(partidas[p].isAutorizado())
                        suma+=Math.round(partidas[p].getCantidadAut()*partidas[p].getPrecioAutCU());
                }
                conv=new BigDecimal(suma);
                t_autorizado.setValue(conv.setScale(2, BigDecimal.ROUND_HALF_UP).doubleValue());
                
                try{
                    t_ref_autorizadas_directo.setValue(orden_act.getRefAutorizadas());
                }catch(Exception e){t_ref_autorizadas_directo.setValue(0.0d);}
                
                if(orden_act.getVales()!=null)
                {
                    this.t_vales.setText(""+orden_act.getVales());
                    this.t_vales.setValue(orden_act.getVales());
                }
                else
                {
                    this.t_vales.setText("0.00");
                    this.t_vales.setValue(0);
                }
                if(orden_act.getValesConsumibles()!=null)
                {
                    this.t_consumibles.setText(""+orden_act.getValesConsumibles());
                    this.t_consumibles.setValue(orden_act.getValesConsumibles());
                }
                else
                {
                    this.t_consumibles.setText("0.00");
                    this.t_consumibles.setValue(0);
                }
                
                
                
            }
        }
        catch(Exception e){e.printStackTrace();}
        if(session!=null)
            if(session.isOpen())
                session.close();
    }
    
    private void doClose() {
        h= new Herramientas(usr, menu);
        h.desbloqueaOrden();
        this.setVisible(false);
    }
}
