/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Servicios;

import Integral.ExtensionFileFilter;
import Integral.Imagen;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.awt.image.RenderedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author Sistemas
 */
public class ver extends javax.swing.JDialog {

    /**
     * Creates new form ver
     */
    private int x=600, y=340;
    public String usuario, password, ip, puerto, bd, ruta;
    public ver(java.awt.Frame parent, boolean modal, String ruta) {
        super(parent, modal);
        initComponents();
        this.ruta=ruta;
        //setExtendedState(JFrame.MAXIMIZED_BOTH);
        p_centro.removeAll();
        ImageIcon img=new ImageIcon(ruta);
        x=img.getIconWidth();
        y=img.getIconHeight();
        p_centro.add(new Imagen(ruta, x, y, 0, 0, x, y));
        p_centro.setSize(new Dimension(x,y));
        p_centro.setBackground(Color.white);
        p_centro.setPreferredSize(new Dimension(x,y));
        
        js_centro.repaint();
        js_centro.updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p_botones = new javax.swing.JPanel();
        sl_img = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        js_centro = new javax.swing.JScrollPane();
        p_centro = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        p_botones.setBackground(new java.awt.Color(255, 255, 255));

        sl_img.setValue(0);
        sl_img.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                sl_imgAncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        sl_img.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sl_imgStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("(+)Zoom");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Zoom(-)");

        jButton1.setText("Exportar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_botonesLayout = new javax.swing.GroupLayout(p_botones);
        p_botones.setLayout(p_botonesLayout);
        p_botonesLayout.setHorizontalGroup(
            p_botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_botonesLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sl_img, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        p_botonesLayout.setVerticalGroup(
            p_botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_botonesLayout.createSequentialGroup()
                .addGroup(p_botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sl_img, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(p_botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(p_botones, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout p_centroLayout = new javax.swing.GroupLayout(p_centro);
        p_centro.setLayout(p_centroLayout);
        p_centroLayout.setHorizontalGroup(
            p_centroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        p_centroLayout.setVerticalGroup(
            p_centroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 609, Short.MAX_VALUE)
        );

        js_centro.setViewportView(p_centro);

        getContentPane().add(js_centro, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sl_imgAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_sl_imgAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_sl_imgAncestorMoved

    private void sl_imgStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sl_imgStateChanged
        // TODO add your handling code here:
        int n =sl_img.getValue()*20;
        p_centro.removeAll();
        p_centro.add(new Imagen(ruta, x+n, y+n, 0, 0, x+n, y+n));
        p_centro.setSize(x+n,y+n);
        p_centro.setPreferredSize(new Dimension(x+n,y+n));
        js_centro.repaint();
        js_centro.updateUI();
    }//GEN-LAST:event_sl_imgStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        javax.swing.JFileChooser jF1= new javax.swing.JFileChooser();
        jF1.setFileFilter(new ExtensionFileFilter("JPG and JPEG", new String[] { "JPG", "JPEG" }));
        if(jF1.showSaveDialog(null)==jF1.APPROVE_OPTION)
        {
            try
            {
                File origen=new File(ruta);
                File destino = new File(jF1.getSelectedFile().getAbsolutePath()+".jpg");
                BufferedImage dibujoGrande =ImageIO.read(origen);
                ImageIO.write((RenderedImage)dibujoGrande, "jpg", destino); // Salvar la imagen en el fichero*/
            }catch(Exception e){e.printStackTrace();}
        }
    }//GEN-LAST:event_jButton1ActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane js_centro;
    private javax.swing.JPanel p_botones;
    private javax.swing.JPanel p_centro;
    private javax.swing.JSlider sl_img;
    // End of variables declaration//GEN-END:variables
}
