/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Servicios;


import Integral.Imagen;
import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author I.S.C Salvador
 */
public class vista extends javax.swing.JPanel {

    /**
     * Creates new form Elemento
     */
    String ruta;
    String nombre;
    
    public vista(String nombre, String ruta) {
        initComponents();
        this.nombre=nombre;
        this.ruta=ruta;
        Hilo miHilo = new Hilo(this.nombre);
        /*try
        {
            File f=new File(ruta+nombre);
            JFileChooser jf=new JFileChooser();
            jf.setSelectedFile(f);
            javax.swing.JPanel p=new javax.swing.JPanel();
            
            if(f.isDirectory()==true){
                p=new Imagen("imagenes/lines.jpg", 76, 79, 1, 1, 76, 79);
            }
            else
                p=new Imagen(ruta+nombre, 76, 79, 1, 1, 76, 79);
                //p_foto.removeAll();
                p_foto.add(p);
                p_foto.repaint();
                l_nombre.setText(f.getName());
                
        }catch(Exception e)
        {
            e.printStackTrace();
        }*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l_nombre = new javax.swing.JLabel();
        p_foto = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setToolTipText("Doble click para abrir");

        l_nombre.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        l_nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_nombre.setText("nombre del archivo");

        p_foto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 255)));
        p_foto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout p_fotoLayout = new javax.swing.GroupLayout(p_foto);
        p_foto.setLayout(p_fotoLayout);
        p_fotoLayout.setHorizontalGroup(
            p_fotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 76, Short.MAX_VALUE)
        );
        p_fotoLayout.setVerticalGroup(
            p_fotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 79, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(l_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(26, 26, 26)
                    .addComponent(p_foto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(31, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(l_nombre))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(p_foto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents
    public class Hilo implements Runnable
    {
        public Thread t;
        public Hilo(String carpeta) 
        {
            t=new Thread(this,carpeta);
            t.start();
        }
        @Override
        public void run() {
          try
            {
                File f=new File(ruta+nombre);
                javax.swing.JPanel p=new javax.swing.JPanel();
                if(f.isDirectory()==true){
                    p=new Imagen("imagenes/lines.jpg", 76, 79, 1, 1, 76, 79);
                }
                else
                    p=new Imagen(ruta+nombre, 76, 79, 1, 1, 76, 79);
                p_foto.removeAll();
                p_foto.add(p);
                p_foto.repaint();
                l_nombre.setText(f.getName());
                p=null;
            }catch(Exception e)
            {
                e.printStackTrace();
            }  
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel l_nombre;
    public javax.swing.JPanel p_foto;
    // End of variables declaration//GEN-END:variables
}
