/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Servicios;


import Integral.Imagen;
import java.io.File;
import javax.swing.ImageIcon;

/**
 *
 * @author I.S.C Salvador
 */
public class vista extends javax.swing.JPanel {

    /**
     * Creates new form Elemento
     */
    String ruta;
    String nombre, carpeta;
    boolean tipo=false;
    
    public vista(String nombre, String ruta, String carpeta, boolean tipo) {
        initComponents();
        this.nombre=nombre;
        this.carpeta=carpeta;
        this.ruta=ruta;
        this.tipo=tipo;
        Hilo miHilo = new Hilo(this.nombre);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l_nombre = new javax.swing.JLabel();
        l_img = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setToolTipText("Doble click para abrir");

        l_nombre.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        l_nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_nombre.setText("nombre del archivo");

        l_img.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        l_img.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(l_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l_img, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l_img, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_nombre))
        );
    }// </editor-fold>//GEN-END:initComponents
    public class Hilo implements Runnable
    {
        public Thread t;
        public Hilo(String carpeta) 
        {
            t=new Thread(this,carpeta);
            t.start();
        }
        @Override
        public void run() {
          try
            {
                javax.swing.JPanel p=new javax.swing.JPanel();
                p=new Imagen("imagenes/lines.jpg", 76, 79, 1, 1, 76, 79);
                if(nombre.contains(".pdf") || nombre.contains(".PDF"))
                    l_img.setIcon(new ImageIcon("imagenes/pdf.png"));
                else{
                    if(nombre.contains(".doc") || nombre.contains(".DOC"))
                        l_img.setIcon(new ImageIcon("imagenes/word.png"));
                    else{
                        if(nombre.contains(".xls") || nombre.contains(".xls"))
                            l_img.setIcon(new ImageIcon("imagenes/exel.png"));
                        else{
                            if(nombre.contains(".jpg") || nombre.contains(".JPG") || nombre.contains(".png") || nombre.contains(".PNG"))
                                l_img.setIcon(new ImageIcon("imagenes/imagen.png"));
                            else
                            {
                                if(tipo==true)
                                    l_img.setIcon(new ImageIcon("imagenes/file.png"));
                                else
                                    l_img.setIcon(new ImageIcon("imagenes/desconocido.png"));
                            }
                        }
                    }
                }    
                l_nombre.setText(nombre);
                p=null;
            }catch(Exception e)
            {
                e.printStackTrace();
            }  
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel l_img;
    private javax.swing.JLabel l_nombre;
    // End of variables declaration//GEN-END:variables
}
